### ISSUE TITLE
Search for games by summoner name

### ISSUE THREAD

**Issue by blubberbo** [blubberbo/LolPickem#8]
write the api functionality to search for a specific summoner (by name) to judge their games

**Comment by blubberbo** [comment]
This includes:

- [ ] UI elements to search and then select a summoner. #99 
- [ ] Riot API infrastructure to get summoners by name in ng and on server. #100
- [ ] Alterations to the `getGame` endpoint to include an `accountId`. #101
